'use strict';
const{config,int}=require('./config');const memory=require('./memory');const{logger}=require('./logger');
const TIMEOUT_MS=int(process.env.CHARIOW_TIMEOUT_MS,12000);
function apiKey(){return String((config.chariow&&config.chariow.apiKey)||'').trim()}
function storeId(){return String((config.chariow&&config.chariow.storeId)||'').trim()}
function isConfigured(){return Boolean(apiKey())}
async function request(path){if(!isConfigured()){const e=new Error('CHARIOW_API_KEY non configuree : connecteur inactif.');e.code='NOT_CONFIGURED';throw e}const base=((config.chariow&&config.chariow.baseUrl)||'https://api.chariow.com/v1').replace(/\/$/,'');const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const res=await fetch(`${base}${path}`,{headers:{Authorization:`Bearer ${apiKey()}`,Accept:'application/json'},signal:c.signal});if(!res.ok){const b=await res.text().catch(()=> '');throw new Error(`Chariow HTTP ${res.status}: ${b.slice(0,160)}`)}return res.json()}catch(err){if(err.name==='AbortError')throw new Error('Chariow a depasse le delai autorise');throw err}finally{clearTimeout(t)}}
function unwrap(d){if(Array.isArray(d))return d;if(d&&Array.isArray(d.data))return d.data;if(d&&Array.isArray(d.results))return d.results;return[]}
async function listSales({perPage=50,cursor}={}){const p=new URLSearchParams({per_page:String(Math.min(100,perPage))});if(cursor)p.set('cursor',cursor);if(storeId())p.set('store_id',storeId());const d=await request(`/sales?${p.toString()}`);return{sales:unwrap(d),next_cursor:(d&&(d.next_cursor||d.cursor))||null}}
async function syncSales(){if(!isConfigured())return{configured:false,imported:0,reason:'CHARIOW_API_KEY non configuree'};const{sales}=await listSales({perPage:50});let imported=0;for(const sale of sales){const id=String(sale.id||sale.sale_id||'').trim();if(!id)continue;const existing=await memory.list(memory.COLLECTIONS.CONTENT,{limit:300});if(existing.some(r=>r.data&&r.data.kind==='chariow_sale'&&r.data.sale_id===id))continue;await memory.insert(memory.COLLECTIONS.CONTENT,{kind:'chariow_sale',sale_id:id,amount:sale.amount!=null?sale.amount:(sale.total!=null?sale.total:null),currency:sale.currency||null,product:sale.product_name||sale.product||null,status:sale.status||'unknown',at:sale.created_at||new Date().toISOString()});await memory.recordEvent('chariow.sale',{sale_id:id,amount:sale.amount!=null?sale.amount:sale.total,source:'chariow'});imported+=1}logger.info('chariow: sync ventes',{imported,total:sales.length});return{configured:true,imported,total_recus:sales.length}}
function status(){return{plateforme:'chariow',configure:isConfigured(),boutique:storeId()||null,statut:isConfigured()?'configuree':'cle_api_manquante',note:isConfigured()?'Cle serveur presente ; ventes synchronisees via API officielle et Pulses.':'Definir CHARIOW_API_KEY (et optionnellement CHARIOW_STORE_ID) dans les variables Netlify, cote serveur uniquement.'}}
module.exports={isConfigured,listSales,syncSales,status};
